function x = get_key(row_freq, col_freq)
[row_freqs, col_freqs] = get_key_freq();
key_board = [ ...
    '1', '2', '3', 'A'; ...
    '4', '5', '6', 'B'; ...
    '7', '8', '9', 'C'; ...
    '*', '0', '#', 'D'; ...
    ];
[~, row_idx] = min(abs(row_freqs - row_freq));
[~, col_idx] = min(abs(col_freqs - col_freq));
x = key_board(row_idx, col_idx);
end
